# Generated by Django 4.2.13 on 2024-05-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('list_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.listtemplate')),
            ],
        ),
    ]
